// Code generated by MockGen. DO NOT EDIT.
// Source: services/mongo_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMongoService is a mock of MongoService interface.
type MockMongoService struct {
	ctrl     *gomock.Controller
	recorder *MockMongoServiceMockRecorder
}

// MockMongoServiceMockRecorder is the mock recorder for MockMongoService.
type MockMongoServiceMockRecorder struct {
	mock *MockMongoService
}

// NewMockMongoService creates a new mock instance.
func NewMockMongoService(ctrl *gomock.Controller) *MockMongoService {
	mock := &MockMongoService{ctrl: ctrl}
	mock.recorder = &MockMongoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMongoService) EXPECT() *MockMongoServiceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockMongoService) Find(ctx context.Context, collection string, filter interface{}) ([]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, collection, filter)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMongoServiceMockRecorder) Find(ctx, collection, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMongoService)(nil).Find), ctx, collection, filter)
}

// Insert mocks base method.
func (m *MockMongoService) Insert(ctx context.Context, collection string, document interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, collection, document)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockMongoServiceMockRecorder) Insert(ctx, collection, document interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMongoService)(nil).Insert), ctx, collection, document)
}
